using System.Text.Json.Serialization;

namespace EZRadiusClient.Models;

public class ServerCAModel
{
    public ServerCAModel() { }
    
    [JsonPropertyName("SubjectName")]
    public string SubjectName { get; set; } = string.Empty;

    [JsonPropertyName("Thumbprint")]
    public string Thumbprint { get; set; } = string.Empty;

    [JsonPropertyName("PendingCSR")]
    public string? PendingCSR { get; set; } = string.Empty;

    [JsonPropertyName("CertificatePEM")]
    public string? CertificatePEM { get; set; } = string.Empty;

    [JsonPropertyName("EZCAEnabled")]
    public bool EZCAEnabled { get; set; } = true;

    [JsonPropertyName("AutoGenerated")]
    public bool AutoGenerated { get; set; }

    [JsonPropertyName("EZCAInstanceForCertificate")]
    public string? EZCAInstanceForCertificate { get; set; } = string.Empty; //used for auto-renewal

    [JsonPropertyName("EZCACAID")]
    public string? EZCACAID { get; set; }

    [JsonPropertyName("EZCATemplateID")]
    public string? EZCATemplateID { get; set; }

    [JsonPropertyName("ExpirationDate")]
    public DateTime? ExpirationDate { get; set; }

    [JsonPropertyName("RootCACertificatePEM")]
    public string? RootCACertificatePEM { get; set; }

    [JsonPropertyName("IntermediateCertificatePEM")]
    public string? IntermediateCertificatePEM { get; set; }
}