name: Build Nuget

on:
  workflow_dispatch:
    inputs:
      version:
        description: EZRADIUS Client Version
        required: true
        default: '1.0.0'
jobs:

  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EZRADIUS_CLIENT_DEPLOYER  }}
      - name: Install SignTool
        run: dotnet tool install --global  AzureSignTool
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Run Powershell Script 
        run: .\EZRadiusClient\CreateNuget.ps1 -nugetVersion ${{ inputs.version}}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: .\EZRadiusClient\bin\Release\EZRadiusClient.${{ inputs.version}}.nupkg
