name: Publish NuGet Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet Package Version (e.g., 1.1.0)'
        required: true
        default: '1.1.0'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EZRADIUS_CLIENT_DEPLOYER }}

      - name: Install AzureSignTool
        run: dotnet tool install --global AzureSignTool

      - name: Build NuGet Package
        run: >
          dotnet build .\EZRadiusClient\EZRadiusClient.csproj
          -c Release -p:Version=${{ inputs.version }}

      - name: Sign NuGet Package
        run: |
          $akvToken = (az account get-access-token --resource https://vault.azure.net --query "accessToken").Replace('"','')
          azuresigntool sign --azure-key-vault-url https://codesigningkeytos.vault.azure.net/ -kvc globalsign --azure-key-vault-accesstoken $akvToken -tr http://timestamp.digicert.com .\EZRadiusClient\bin\Release\EZRadiusClient.${{ inputs.version }}.nupkg
        shell: pwsh

      - name: Verify NuGet Package
        run: >
          dotnet nuget verify --all
          .\EZRadiusClient\bin\Release\EZRadiusClient.${{ inputs.version }}.nupkg

      - name: Publish to NuGet.org
        run: >
          dotnet nuget push
          .\EZRadiusClient\bin\Release\EZRadiusClient.${{ inputs.version }}.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: >
            .\EZRadiusClient\bin\Release\EZRadiusClient.${{ inputs.version }}.nupkg
